version: '3'
services:
  radicle:
    container_name: radicle
    hostname: radicle
    build:
      context: ./radicle-bins/
      dockerfile: Dockerfile
    ports:
       - 80:80
       - 12345:12345
    volumes:
      - ./root:/root
